=== zopenge/EasyGameEngine/Document/FileFormat/GenerateFromXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 被2011 rel. 2 sp1 (TeaM DJiNN) 使用XMLSpy vTeaM DJiNN编辑的 (http://www.altova.com) by -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://your_namespace" targetNamespace="http://your_namespace" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:attributeGroup name="AttributeGroup">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="display_name" type="xs:string" use="optional"/>
		<xs:attribute name="comment" type="xs:string" use="optional"/>
	</xs:attributeGroup>
	<xs:element name="enumeration_item">
		<xs:complexType>
			<xs:attributeGroup ref="AttributeGroup"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="enumeration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enumeration_item" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attributeGroup ref="AttributeGroup"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="variable">
		<xs:complexType>
			<xs:attributeGroup ref="AttributeGroup"/>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="min" type="xs:float" use="optional"/>
			<xs:attribute name="max" type="xs:float" use="optional"/>
			<xs:attribute name="default" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="struct">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="variable" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="struct" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attributeGroup ref="AttributeGroup"/>
			<xs:attribute name="is_serializable" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="function">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="variable" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="struct" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attributeGroup ref="AttributeGroup"/>
			<xs:attribute name="ret_type" type="xs:string" use="required"/>
			<xs:attribute name="is_const" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enumeration" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="function" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attributeGroup ref="AttributeGroup"/>
			<xs:attribute name="parent" type="xs:string" use="optional" default="IObject"/>
			<xs:attribute name="is_interface" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Root"/>
</xs:schema>

=== zopenge/EasyGameEngine/Document/FileFormat/GenerateFromXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--用XMLSpy v2011 rel. 2 sp1产生的 XML文件(http://www.altova.com)-->
<Root xsi:schemaLocation="http://your_namespace GenerateFromXSD.xsd" xmlns="http://your_namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<enumeration name="_SCENE_TYPE">
		<enumeration_item name="_SCENE_TYPE_UNKNOWN" display_name="Unknown"/>
		<enumeration_item name="_SCENE_TYPE_SIMPLE" display_name="Simple"/>
		<enumeration_item name="_SCENE_TYPE_COMPLEX" display_name="Complex"/>
	</enumeration>
	<enumeration name="_SCENE_SORT">
		<enumeration_item name="_SCENE_SORT_UNKNOWN" display_name="xUnknown"/>
		<enumeration_item name="_SCENE_SORT_SIMPLE" display_name="xSimple"/>
		<enumeration_item name="_SCENE_SORT_COMPLEX" display_name="xComplex"/>
	</enumeration>
	<struct name="SceneInfo" is_serializable="true">
		<variable type="_ubool" name="mIsExist" display_name="IsExist" default="false"/>
		<variable type="_ubool" name="mIsPlaying" display_name="IsPlaying" default="false"/>
		<variable type="_SCENE_TYPE" name="mSceneType" display_name="SceneType" default="_SCENE_TYPE_UNKNOWN" comment="The type of scene"/>
		<variable type="_dword" name="mValue" display_name="Value" default="100" min="100" max="4000"/>
		<struct name="SceneInfoEmbedded">
			<variable type="WString" name="mName" display_name="Name" default="NA" comment="Name of embedded"/>
		</struct>
	</struct>
	<class name="IScene" is_interface="true" parent="IObject">
		<enumeration name="_SCENE_TYPE"></enumeration>
		<function name="GetInfo" ret_type="SceneInfo&amp;" is_const="true" comment="Get scene info"/>
		<function name="GetSceneType" ret_type="_SCENE_TYPE" is_const="true" comment="Get scene type"/>
	</class>
</Root>
